# Generated by Django 5.2.1 on 2025-05-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='referred_by',
        ),
    ]
