# Generated by Django 5.2.1 on 2025-05-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_depositrequest_delete_cryptoaddress_delete_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
