# Generated by Django 5.2.1 on 2025-05-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_depositrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('address', models.CharField(max_length=255)),
                ('txn_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('network_name', models.CharField(max_length=50)),
                ('explorer_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='converted_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
